Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2019-10, with the labels that each got.

#18 fix infrastructure. OMPVV.F90 modifies argument that is in read only memory
  ompvv/ompvv.F90
Labels: Infrastructure, bug

#4 New test/test target enter data classes
  tests/4.5/target_enter_data/test_target_enter_data_classes.cpp
  tests/4.5/target_enter_data/test_target_enter_data_classes_inheritance.cpp
  tests/4.5/target_enter_data/test_target_enter_data_classes_simple.cpp
Labels: bug

#27 Verification issue in test `mmm_target.c`
  tests/4.5/application_kernels/mmm_target.c
Labels: bug

#26 Data race and verification issue in test `mmm_target_parallel_for_sim…
  tests/4.5/application_kernels/mmm_target_parallel_for_simd.c
Labels: bug

#3 New test/test target teams distribute nowait
  tests/4.5/target_teams_distribute/test_target_teams_distribute_nowait.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_nowait.c
Labels: new test

#21 new_test/test_target_teams_distribute_parallel_for_schedule_private.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_schedule_private.c
Labels: new test
