Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2019-12, with the labels that each got.

#19 Fixing test test_target_teams_distribute_parallel_for_firstprivate.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_firstprivate.c
Labels: bug

#30 Changing allocation of memory to heap instead of stack to fix issue #14
  tests/4.5/target_teams_distribute/test_target_teams_distribute_collapse.c
Labels: bug

#20 New test/test target teams distribute num teams
  tests/4.5/target_teams_distribute/test_target_teams_distribute_num_teams.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_num_teams.c
Labels: new test

#40 New feature/adding online report
  .gitignore
  Makefile
  sys/scripts/API/__init__.py
  sys/scripts/API/sollve_api.py
  sys/scripts/onlineConnection.py
Labels: Infrastructure, enhancement

#39 New feature/adding git commit to log header
  Makefile
  sys/make/make.def
  sys/results_template/css/fonts/glyphicons-halflings-regular.eot
  sys/results_template/css/fonts/glyphicons-halflings-regular.svg
  sys/results_template/css/fonts/glyphicons-halflings-regular.ttf
  sys/results_template/css/fonts/glyphicons-halflings-regular.woff
  sys/results_template/css/fonts/glyphicons-halflings-regular.woff2
  sys/results_template/js/results.js
  sys/results_template/results.html
  sys/scripts/createSummary.py
Labels: Infrastructure, enhancement

#43 Addition of condensed summary to `make report_summary`
  sys/scripts/createSummary.py
Labels: Infrastructure, enhancement

#32 New test/test target teams distribute lastprivate
  tests/4.5/target_teams_distribute/test_target_teams_distribute_lastprivate.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_lastprivate.c
Labels: new test
