Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2020-09, with the labels that each got.

#160 New 5.0 test for nested declare target
  tests/5.0/declare_target/test_declare_target_nested.c
  tests/5.0/declare_target/test_declare_target_nested_functions.c
Labels: 5.0, new test, ready

#86 New test/require unified shared memory
  tests/5.0/requires/test_requires_unified_shared_memory.c
  tests/5.0/requires/test_requires_unified_shared_memory_heap.c
  tests/5.0/requires/test_requires_unified_shared_memory_heap_is_device_ptr.c
  tests/5.0/requires/test_requires_unified_shared_memory_heap_map.c
  tests/5.0/requires/test_requires_unified_shared_memory_omp_target_alloc.c
  tests/5.0/requires/test_requires_unified_shared_memory_omp_target_alloc_is_device_ptr.c
  tests/5.0/requires/test_requires_unified_shared_memory_stack.c
  tests/5.0/requires/test_requires_unified_shared_memory_stack_is_device_ptr.c
  tests/5.0/requires/test_requires_unified_shared_memory_stack_map.c
  tests/5.0/requires/test_requires_unified_shared_memory_static.c
  tests/5.0/requires/test_requires_unified_shared_memory_static_is_device_ptr.c
  tests/5.0/requires/test_requires_unified_shared_memory_static_map.c
Labels: 5.0, in progress, new test

#190 Adding test motivated by QMCPack.
  tests/4.5/task/test_target_and_task_nowait.c
Labels: ready

#194 Fix minor issues in test_target_update_mapper_to_discontiguous.c
  tests/5.0/target_update/test_target_update_mapper_to_discontiguous.c
Labels: awaiting testing

#202 New feature/target thread team macros (for issue #22)
  tests/4.5/target/test_target_firstprivate.F90
  tests/4.5/target/test_target_firstprivate.c
  tests/4.5/target/test_target_private.F90
  tests/4.5/target/test_target_private.c
Labels: infrastructure, ready

#78 Add declare target subroutine test from CORAL-2 (issue #60)
  tests/4.5/application_kernels/declare_target_subroutine.F90
Labels: new test, ready

#207 Adding one-line fix to address problems described in issue 203
  tests/4.5/target_enter_data/test_target_enter_data_if.F90
Labels: V&V bug, ready

#205 Target teams distribute thread team macros (issue #22)
  ompvv/ompvv.F90
  ompvv/ompvv.h
  tests/4.5/target_teams_distribute/test_target_teams_distribute_collapse.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_collapse.c
  tests/4.5/target_teams_distribute/test_target_teams_distribute_default_none.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_default_none.c
  tests/4.5/target_teams_distribute/test_target_teams_distribute_default_private.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_firstprivate.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_firstprivate.c
  tests/4.5/target_teams_distribute/test_target_teams_distribute_shared.c
Labels: enhancement, infrastructure, ready

#206 Target teams distribute parallel for thread team macros (issue #22)
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_firstprivate.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_if_no_modifier.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_if_parallel_modifier.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_if_target_modifier.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_num_teams.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_schedule_private.c
  tests/5.0/teams/test_teams.c
  tests/5.0/teams/test_teams_distribute_default_none.c
Labels: enhancement, infrastructure, ready
