Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2020-05, with the labels that each got.

#134 Fix issue #128, uninit arrays in reduction_bitand.F90 and bitor
  tests/4.5/target_teams_distribute/test_target_teams_distribute_reduction_bitand.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_reduction_bitor.F90
  tests/5.0/target_teams_distribute/test_target_teams_distribute_reduction_bitand.F90
  tests/5.0/target_teams_distribute/test_target_teams_distribute_reduction_bitor.F90
Labels: bug fix, ready

#136 Another possible solution.
  tests/4.5/target/test_target_private.c
Labels: bug fix, ready

#130 Fix for issue #109
  tests/4.5/target_teams_distribute/test_target_teams_distribute_firstprivate.F90
Labels: bug fix, ready

#139 test_target_teams_distribute_collapse.F90 – wrong map flag #138
  tests/4.5/target_teams_distribute/test_target_teams_distribute_collapse.F90
Labels: bug fix, ready

#144 Resolving issues #31 and #97
  tests/4.5/target/test_target_private.F90
Labels: bug fix, ready

#142 New test/team/test_team_distribute_default_none.c
  tests/5.0/teams/test_teams_distribute_default_none.c
Labels: 5.0, ready

#131 Add fixed version of default_firstprivate test
  tests/4.5/target_teams_distribute/test_target_teams_distribute_default_firstprivate.F90
Labels: bug fix, ready

#143 Remove shared env macro from target and target data tests
  template/ompvv_template.F90
  template/ompvv_template.c
  tests/4.5/target/test_target_map_module_array.F90
  tests/4.5/target/test_target_map_program_arrays.F90
  tests/4.5/target/test_target_map_subroutines_arrays.F90
  tests/4.5/target_data/test_target_data_if.F90
  tests/4.5/target_data/test_target_data_if.c
  tests/4.5/target_data/test_target_data_map.F90
  tests/4.5/target_data/test_target_data_map_components_from.F90
  tests/4.5/target_data/test_target_data_map_components_to.F90
  tests/4.5/target_data/test_target_data_map_devices.F90
  tests/4.5/target_data/test_target_data_map_from_array_sections.F90
  tests/4.5/target_data/test_target_data_map_set_default_device.F90
  tests/4.5/target_data/test_target_data_map_to_array_sections.F90
  tests/4.5/target_data/test_target_data_pointer_swap.c
Labels: bug fix, infrastructure, ready

#132 Auto-detect GCC and clang versions
  sys/make/make.def
Labels: enhancement, under discussion

#146 Adding top-of-file comments
  tests/4.5/target/test_target_defaultmap.c
  tests/4.5/target/test_target_depends.c
Labels: enhancement, ready

#104 Testing invocation of math functions inside target region.
  tests/4.5/application_kernels/qmcpack_target_math.c
Labels: new test, ready

#141 test_target_teams_distribute_parallel_for_devices.c: wrong check, mul…
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_devices.c
Labels: bug fix

#150 Test for team construct on host with default(shared) clause.
  tests/5.0/teams/test_team_default_shared.c
Labels: 5.0, new test, ready

#149 Minor fixes to detect GCC and clang versions
  sys/make/make.def
Labels: ready

#71 Fix test/target enter exit data/test target enter exit data classes.cpp
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_classes.cpp
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_classes_complex.cpp
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_classes_simple.cpp
Labels: V&V bug, enhancement, report bug

#117 Modifying test_target_enter_exit_data_if.c to use headerfile
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_if.c
Labels: enhancement, in progress
