Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2020-04, with the labels that each got.

#125 Fix test/test target teams distribute thread limit
  tests/4.5/target_teams_distribute/test_target_teams_distribute_thread_limit.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_thread_limit.c
Labels: bug fix

#133 Addressing issue #122
  tests/4.5/target_data/test_target_data_map_alloc.c
  tests/4.5/target_data/test_target_data_map_from.c
  tests/4.5/target_data/test_target_data_map_to.c
Labels: bug fix, ready

#120 QMCPACK target static lib test and add OMPVV static lib
  .gitignore
  Makefile
  ompvv/libompvv.c
  ompvv/libompvv.h
  tests/4.5/application_kernels/qmcpack_target_static_lib.c
Labels: Makefile, infrastructure, new test, ready

#126 Fixing file to issue warning and fail when run host, instead of crashing
  tests/4.5/target/test_target_is_device_ptr.c
Labels: bug fix, ready
