Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2020-02, with the labels that each got.

#89 Fix Macro Usage and Formatting Issues in fix_test/test_target_enter_e…
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_struct.c
Labels: enhancement

#77 New test/reduction separated directives.c (issue #35)
  tests/4.5/application_kernels/reduction_separated_directives.c
  tests/4.5/application_kernels/reduction_separated_directives.cpp
Labels: new test

#92 Fix test/test enter exit data map malloced array.c to add delete testing and fix issue #10
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_map_malloced_array.c
Labels: enhancement

#69 Fixing fix_test/test_target_map_pointer.c to use headerfile
  tests/4.5/target/test_target_map_pointer.c
Labels: enhancement, ready

#57 Add Fortran version of shared test and minor cleanup
  tests/4.5/target_teams_distribute/test_target_teams_distribute_shared.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_shared.c
Labels: new test

#88 Bug fix for test_target_teams_distribute_reduction_sub.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_reduction_sub.F90
Labels: bug fix

#91 Change the header file to address issue #79
  ompvv/ompvv.h
Labels: enhancement, ready

#99 Add declare_target_module test from CORAL-2
  tests/4.5/application_kernels/declare_target_module.F90
Labels: new test

#95 Fixing macro usage and adding additional test function
  tests/4.5/target/test_target_map_scalar_default.c
  tests/4.5/target/test_target_map_scalar_no_map_type_modifier.c
Labels: enhancement

#93 Modifying test_target_map_pointer.default.c to use headerfile, as per…
  tests/4.5/target/test_target_map_pointer_default.c
  tests/4.5/target/test_target_map_pointer_no_map_type_modifier.c
  tests/4.5/target/test_target_map_zero_length_pointer.c
Labels: enhancement, ready

#102 Modifying test to use headerfile (Issue #10)
  tests/4.5/target/test_target_map_struct_default.c
Labels: enhancement, ready

#103 Modifying test_target_private.c to use headerfile (Issue #10)
  tests/4.5/target/test_target_private.c
Labels: enhancement, ready
