Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2020-10, with the labels that each got.

#213 Issue 212: test_target_teams_distribute_reduction_bitor.c use inited var
  tests/5.0/target_teams_distribute/test_target_teams_distribute_reduction_bitor.c
Labels: bug fix, ready

#211 Update test_target_teams_distribute_parallel_for_devices.c (issue #9)
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_devices.c
Labels: bug fix, ready

#210 Add 5.0 test of simd inside atomic for C
  tests/5.0/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_simd_atomic.c
Labels: 5.0, new test, ready

#84 Test for the iterator modifier inside task depend on OMP 5.0
  tests/5.0/tasks/test_task_depend_iterator.cpp
Labels: 5.0, new test, ready

#217 header filename fix
  tests/5.0/teams/test_teams_distribute_default_none.c
Labels: ready

#209 F90 5.0 test for declare mapper
  tests/5.0/declare_mapper/test_declare_mapper_target_struct.F90
Labels: 5.0, new test, ready

#208 F90 5.0 test for target update
  tests/5.0/target_update/test_target_update_mapper_to_discontiguous.F90
Labels: 5.0, new test, ready

#220 Update test_target_and_task_nowait.c
  tests/4.5/task/test_target_and_task_nowait.c
Labels: bug fix, ready

#218 New test/test task detach.c
  tests/5.0/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_simd_atomic.c
  tests/5.0/task/test_task_detach.c
Labels: 5.0, new test, ready

#165 Imperfect loop collapse
  tests/5.0/target/test_target_imperfect_loop.c
Labels: 5.0, in progress

#224 Add code to log omp version in reports
  Makefile
  sys/make/make.def
  sys/scripts/createSummary.py
Labels: enhancement, infrastructure, ready

#223 Fixing make.def to load modules before getting version info for gcc, clang
  sys/make/make.def
  sys/systems/summit.def
Labels: bug fix, infrastructure, ready
