Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2020-07, with the labels that each got.

#173 Correct LICENSE name
  LICENSE
Labels: ready

#166 Addressing #162, switching undeclared var 'threshold' with 'N'
  tests/5.0/target_teams_distribute/test_target_teams_distribute_reduction_bitor.c
Labels: bug fix, ready

#121 Add tulip.def, AMD compiler flags for Cray CCE, and DEVICE_TYPE Makefile option
  Makefile
  sys/make/make.def
  sys/systems/summit.def
  sys/systems/tulip.def
Labels: Makefile, infrastructure
