Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2021-12, with the labels that each got.

#427 Issue 426: Free device vars before stack-local var lifetime ends
  tests/4.5/target_enter_data/test_target_enter_data_depend.c
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_depend.c
Labels: enhancement, 4.5

#385 Adding .F90 test for test_target_update_devices.F90
  tests/4.5/target_update/test_target_update_devices.F90
Labels: new test, ready

#413 Adding -fopenmp-version flags for clang/clang++ to make.def file
  sys/make/make.def
Labels: enhancement
