Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2021-08, with the labels that each got.

#366 taskwait depend
  tests/5.0/taskwait/test_taskwait_depend.c
Labels: new test, 5.0, ready

#360 Add test of in_reduction nested in function from issue #50
  tests/5.0/task/test_task_in_reduction_dynamically_enclosed.c
Labels: new test, 5.0, ready

#381 Reducing loop size to avoid potential overflow - issue #380
  tests/4.5/target_teams_distribute/test_target_teams_distribute_reduction_bitand.F90
Labels: ready, bug fix

#376 Adding missing include statement and making other small style changes
  tests/4.5/target_enter_data/test_target_enter_data_global_array.c
Labels: 5.0, ready, bug fix

#336 Update test_target_enter_data_classes_inheritance.cpp
  tests/4.5/target_enter_data/test_target_enter_data_classes_inheritance.cpp
Labels: ready, bug fix

#388 Fix for test test_target_teams_distribute_reduction_bitand.F90
  tests/5.0/target_teams_distribute/test_target_teams_distribute_reduction_bitand.F90
Labels: ready, bug fix

#389 Addressing test miscrediting openmp examples
  tests/5.0/declare_variant/test_declare_variant.F90
Labels: ready, bug fix

#358 Test target update mapper from discontiguous
  tests/5.0/target_update/test_target_update_mapper_from_discontiguous.c
Labels: 5.0, ready

#391 Adding tests to check hint specified by numeric value.
  tests/5.0/atomic/test_atomic_num_hint.c
  tests/5.0/atomic/test_atomic_num_hint_device.c
Labels: new test, 5.0, ready

#386 Atomic Compare Test
  tests/5.1/atomic/test_atomic_compare.c
Labels: new test, ready, 5.1
