Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2021-11, with the labels that each got.

#405 Fix metadirectives testcases
  tests/5.0/metadirective/test_metadirective_arch_is_nvidia.c
  tests/5.0/metadirective/test_metadirective_arch_nvidia_or_amd.c
Labels: 5.0, bug fix

#403 Target Update w/ Motion Modifier Present
  tests/5.1/motion/test_motion_present.c
Labels: new test, ready, 5.1

#411 Adding -qopenmp flag for Intel ICX, ICPX, IFX compilers in Make.def
  sys/make/make.def
Labels: Makefile

#396 Fixing reverse_offload test per issue #393
  tests/5.0/requires/test_requires_reverse_offload.c
Labels: enhancement, bug fix, awaiting testing

#414 Fixing and renaming test for target update to with present
  tests/5.1/target_update/test_target_update_to_present.c
Labels: enhancement, 5.1

#355 5.0 Fortran tests of task affinity
  tests/5.0/task/test_task_affinity.F90
  tests/5.0/task/test_task_affinity_device.F90
Labels: new test, 5.0, awaiting testing

#354 5.0 C test of task with affinity clause
  tests/5.0/task/test_task_affinity.c
  tests/5.0/task/test_task_affinity_device.c
Labels: new test, 5.0, bug filed, under discussion

#412 Adding new .def entry for nvidia compilers (nvc,nvc++,nvfotran)
  sys/make/make.def
Labels: enhancement

#415 Fix memleak in tests/5.0/task/test_task_affinity*.c
  tests/5.0/task/test_task_affinity.c
  tests/5.0/task/test_task_affinity_device.c
Labels: 5.0, bug fix

#416 Plug memory leaks, fix cast errors
  tests/4.5/application_kernels/linked_list.c
  tests/4.5/application_kernels/mmm_target.c
  tests/4.5/application_kernels/mmm_target_parallel_for_simd.c
  tests/4.5/application_kernels/omp_default_device.c
  tests/4.5/target_data/test_target_data_map_devices.c
  tests/4.5/target_enter_data/test_target_enter_data_depend.c
  tests/4.5/target_enter_data/test_target_enter_data_global_array.c
  tests/4.5/target_enter_data/test_target_enter_data_struct.c
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_depend.c
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_map_malloced_array.c
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_struct.c
  tests/4.5/target_simd/test_target_simd_collapse.c
  tests/4.5/target_teams_distribute/test_target_teams_distribute_collapse.c
  tests/4.5/target_teams_distribute/test_target_teams_distribute_is_device_ptr.c
  tests/4.5/target_update/test_target_update_depend.c
  tests/5.0/loop/test_loop_collapse.c
  tests/5.0/loop/test_loop_collapse_device.c
  tests/5.0/taskgroup/test_taskgroup_task_reduction_device.c
Labels: bug fix

#418 Fix enum conversion and int overflow
  tests/4.5/application_kernels/declare_target_subroutine.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_defaultmap.c
  tests/4.5/target_teams_distribute/test_target_teams_distribute_nowait.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_nowait.c
Labels: bug fix

#419 Issue 417: Only call permitted routines strictly nested in 'teams'
  tests/5.0/loop/test_loop_bind.c
  tests/5.0/loop/test_loop_bind_device.c
  tests/5.0/loop/test_loop_nested.c
  tests/5.0/loop/test_loop_nested_device.c
  tests/5.0/teams/test_teams.F90
  tests/5.0/teams/test_teams.c
Labels: enhancement

#422 Issue 421: 5.0/task/test_task_affinity_device.c fix for nonshared memory
  tests/5.0/task/test_task_affinity_device.c
Labels: 5.0, ready, bug fix

#425 Resolving race in test_taskwait_depend.c
  tests/5.0/taskwait/test_taskwait_depend.c
Labels: 5.0, bug fix
