Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2022-01, with the labels that each got.

#390 Defaultmap with Present Clause
  tests/5.1/target/test_target_defaultmap_present.c
Labels: ready, report bug, 5.1

#432 Adding new 5.1 test for defaultmap with present clause for scalars
  tests/5.1/target/test_target_defaultmap_present_scalar.c
Labels: ready, report bug, 5.1

#433 Default w/ Firstprivate - Parallel Construct
  tests/5.1/default/test_default_firstprivate_parallel.c
Labels: new test, 5.1

#359 Add sequential loop tile transformation test in C on the host
  tests/5.1/tile/test_tile.c
Labels: new test, ready, 5.1

#371 Adding 3 new .F90 tests per issue #81 and fixing related .c files - pt 4
  tests/4.5/target_parallel/test_target_parallel.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_num_teams.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_num_teams.c
  tests/4.5/target_update/test_target_update_from.F90
Labels: enhancement, new test, ready

#435 Correcting allocation.
  tests/5.0/allocate/test_allocate_allocator.c
Labels: 5.0, ready, bug fix

#444 Test is invalid.
  tests/5.0/target/test_target_mapping_before_delete.F90
Labels: 5.0, ready, bug fix

#443 Moving tests to appropriate folders
  tests/5.1/cpp_attribute_specifier/test_cpp_attribute_specifier.cpp
  tests/5.1/declare_variant/test_begin_end_declare_variant.c
Labels: ready, 5.1

#369 Adding 3 new .F90 tests per issue #81 and fixing .c files
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_devices.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_firstprivate.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_private.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_private.c
Labels: enhancement, new test, ready

#373 Adding test_target_enter_exit_data_depend.F90 per issue #81
  tests/4.5/target_enter_data/test_target_enter_data_allocate_array_to.F90
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_depend.F90
  tests/4.5/target_enter_exit_data/test_target_enter_exit_data_depend.c
Labels: enhancement, new test, ready

#447 Update test_target_defaultmap_default.c
  tests/5.0/target/test_target_defaultmap_default.c
Labels: ready
