Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2022-08, with the labels that each got.

#568 omp_target_memcpy_rect_async test
  tests/5.1/target/test_target_memcpy_async_depobj.c
  tests/5.1/target/test_target_memcpy_async_no_obj.c
  tests/5.1/target/test_target_memcpy_rect_async_depobj.c
  tests/5.1/target/test_target_memcpy_rect_async_no_obj.c
Labels: new test, in progress, ready, 5.1

#588 Update Makefile
  Makefile
Labels: Makefile, ready

#576 scope construct private test
  tests/5.1/scope/test_scope_private_construct.c
Labels: ready, 5.1

#594 Fix tests using fprintf in GPU target region
  tests/5.0/target_requires/test_target_requires_atomic_default_mem_order_acq_rel.c
  tests/5.0/target_requires/test_target_requires_atomic_default_mem_order_relaxed.c
  tests/5.0/target_requires/test_target_requires_atomic_default_mem_order_seq_cst.c
Labels: ready, bug fix

#575 Omp_is_accessible new test version
  tests/5.1/target/test_target_is_accessible.c
Labels: new test, ready, 5.1

#562 scope reduction construct test
  tests/5.1/scope/test_scope_reduction_construct.c
Labels: new test, ready, 5.1

#605 test_scope_reduction_construct.c: Init loop variable
  tests/5.1/scope/test_scope_reduction_construct.c
Labels: ready, bug fix, 5.1

#609 Change the createSummary.py to support utf-8 log files
  sys/scripts/createSummary.py
Labels: ready, bug fix

#607 ompvv/ompvv.h: Parenthesize error condition in OMPVV_REPORT+OMPVV_RETURN
  ompvv/ompvv.h
Labels: enhancement, Makefile, ready

#603 Fix tests/5.1/scope/test_scope_private_construct.c
  tests/5.1/scope/test_scope_private_construct.c
Labels: bug fix
