Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2022-04, with the labels that each got.

#502 Fortran: Make standard conform, avoid conversion warnings
  tests/4.5/target/test_target_defaultmap.F90
  tests/4.5/target_teams_distribute/test_target_teams_distribute_defaultmap.F90
Labels: enhancement, ready

#508 Fixing issue where test does not properly check for offloading
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_if_parallel_modifier.F90
Labels: ready, bug fix

#504 test_requires_dynamic_allocators.F90: Free allocator/var inside target
  tests/5.0/requires/test_requires_dynamic_allocators.F90
Labels: enhancement, ready

#463 Add tests/5.0/target/test_target_imperfect_loop.F90
  tests/5.0/target/test_target_imperfect_loop.F90
  tests/5.0/target/test_target_imperfect_loop.c
Labels: new test, 5.0, ready

#462 compiler not allowing default(private) as a valid data-sharing type
  tests/5.1/default/test_task_default_private.c
Labels: ready, 5.1

#481 Add new_test/test_parallel_master_taskloop_simd.F90
  tests/5.0/parallel_master_taskloop_simd/test_parallel_master_taskloop_simd.F90
  tests/5.0/parallel_master_taskloop_simd/test_parallel_master_taskloop_simd.c
Labels: new test, 5.0, ready

#480 Add new_test/test_parallel_master_taskloop_simd_device.F90
  tests/5.0/parallel_master_taskloop_simd/test_parallel_master_taskloop_simd_device.F90
  tests/5.0/parallel_master_taskloop_simd/test_parallel_master_taskloop_simd_device.c
Labels: new test, 5.0, ready

#513 Adding amdclang, amdclang++, and amdflang flags to make.def file
  sys/make/make.def
Labels: enhancement, ready

#470 Add tests/5.0/parallel_for/test_parallel_for_order_concurrent.F90
  tests/5.0/parallel_for/test_parallel_for_order_concurrent.F90
Labels: new test, 5.0, ready

#500 Fix test_target_teams_distribute_parallel_for_devices.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_devices.F90
Labels: bug fix

#497 omp_target_memcpy_async TEST with no dependent object
  tests/5.1/target/test_target_memcpy_async_no_obj.c
Labels: new test, ready, 5.1

#382 Adding test for target_teams_distribute_parallel_for_if with target modifier
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_if_target_modifier.F90
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_if_target_modifier.c
Labels: new test, ready

#515 ompvv/ompvv.F90: Guard a PARAMETER by #ifdef
  ompvv/ompvv.F90
Labels: bug fix

#526 Update make.def amdclang entry
  sys/make/make.def
Labels: ready, bug fix
