Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2024-05, with the labels that each got.

#785 Adding test cases for target teams distribute parallel for schedule and reduction clause
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_dist_schedule.c
  tests/4.5/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_reduction.c
Labels: in progress, 4.5

#811 6.0 nowait test.
  tests/6.0/target/test_target_nowait_argument.F90
  tests/6.0/target/test_target_nowait_argument.c
Labels: ready, 6.0

#821 Fix overflow on tests/5.0/target/test_target_firstprivate_device.c
  tests/5.0/target/test_target_firstprivate_device.c
Labels: 5.0, ready, bug fix

#820 Resolving issue 817.
  tests/5.0/target_update/test_target_update_mapper_from_discontiguous.c
Labels: ready, bug fix
