Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2024-04, with the labels that each got.

#702 map virtual function test
  tests/5.1/target/test_virtual_function_map.cpp
Labels: new test, ready, 5.1

#703 Declare Mapper w/ Present
  tests/5.2/declare_mapper/test_declare_mapper_present.c
Labels: new test, in progress, ready, 5.2

#806 4.5/taskloop/test_taskloop_private.c: Init variable
  tests/4.5/taskloop/test_taskloop_private.c
  tests/4.5/taskloop/test_taskloop_simd_shared.c
Labels: ready

#802 Add uses_allocators to fix compiler error
  tests/5.0/target/test_target_allocate.c
Labels: 5.0, ready, bug fix

#800 Change proposal for test_capture_omp_affinity.c
  tests/5.0/program_control/test_capture_omp_affinity.c
Labels: 5.0, ready, bug fix

#803 Fix issue created by mhalk on github
  tests/4.5/taskloop/test_taskloop_num_tasks.c
Labels: ready, bug fix, 4.5

#804 Allow not expected result for const allocator
  tests/5.0/target/test_target_uses_allocators_const.c
Labels: 5.0, ready, bug fix

#793 Parallel sections
  tests/4.5/parallel_sections/test_parallel_sections.c
  tests/5.1/target_teams_distribute_parallel_for/test_target_teams_distribute_parallel_for_default.c
Labels: in progress
