Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2024-01, with the labels that each got.

#788 Flipped values for USM macro var, now default value is zero to indica…
  ompvv/ompvv.h
Labels: ready

#789 test_dispatch_is_device_ptr.c: Avoid accessing device var on the host
  tests/5.1/dispatch/test_dispatch_is_device_ptr.c
Labels: bug fix, 5.1

#784 Adding Test Cases for Target Parallel Loop Construct new
  tests/5.0/target_parallel_loop/test_target_parallel_loop_bind.c
  tests/5.0/target_parallel_loop/test_target_parallel_loop_lastprivate.c
  tests/5.0/target_parallel_loop/test_target_parallel_loop_order.c
  tests/5.0/target_parallel_loop/test_target_parallel_loop_private.c
Labels: in progress, 5.0

#761 Adding more tests with teams loop construct
  tests/5.0/teams_loop/test_target_teams_loop_allocate.c
  tests/5.0/teams_loop/test_target_teams_loop_defaultmap.c
  tests/5.0/teams_loop/test_target_teams_loop_depend.c
  tests/5.0/teams_loop/test_target_teams_loop_is_device_ptr.c
Labels: in progress, 5.0

#736 Adding tests targeting USM feature
  tests/5.2/unified_shared_mem/test_target_OpertrOvrld.cpp
  tests/5.2/unified_shared_mem/test_target_VirDestr.cpp
  tests/5.2/unified_shared_mem/test_target_VirFunc.cpp
  tests/5.2/unified_shared_mem/test_target_class_deepcpy.cpp
  tests/5.2/unified_shared_mem/test_target_mul_inheritence.cpp
  tests/5.2/unified_shared_mem/test_target_mul_inheritence1.cpp
Labels: ready, 5.2

#790 Fix fixed-form Fortran quote and line-length issues
  ompvv/ompvv.F
  tests/5.2/implementation_defined/test_omx_fixed.F
Labels: bug fix

#728 New test for omp_set_num_teams()
  tests/5.1/teams/test_target_set_num_teams.c
Labels: ready, 5.1

#722 Add new_test/5.1/test_target_memcpy_async_depobj.F90
  tests/5.1/target/test_target_memcpy_async_depobj.F90
  tests/5.1/target/test_target_memcpy_async_depobj.c
Labels: new test, in progress, 5.1
