Repository OpenMP-Validation-and-Verification/OpenMP_VV, pull requests merged in 2025-01, with the labels that each got.

#851 Changing the offloading architecture flag from native to frontier specific arch.
  sys/make/make.def
Labels: Makefile

#849 Added notdir comparison to fix issue of being unable to supply absolute paths to compiler definition for the makefile.
  sys/make/make.def
Labels: Makefile, 6.0

#847 New 6.0 test for map with self modifier
  tests/6.0/target/test_target_map_self.c
Labels: in progress, 6.0

#842 New test for groupprivate 6.0
  tests/6.0/groupprivate/test_teams_groupprivate_devicetype_host.c
  tests/6.0/target/test_target_teams_groupprivate.c
  tests/6.0/target/test_target_teams_groupprivate_devicetype_any.c
  tests/6.0/target/test_target_teams_groupprivate_devicetype_nohost.c
Labels: in progress, 6.0
